# Generated by Django 2.2.11 on 2021-06-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20210609_1356'),
        ('users', '0040_auto_20210616_1821'),
    ]

    operations = [
    ]
