# Generated by Django 2.2.11 on 2021-06-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20210609_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='is_dashboard_activated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
