# Generated by Django 2.2.11 on 2021-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0250_auto_20210603_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='expected_type_gaseous',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='expected_type_j_cylinders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='type_gaseous',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='type_j_cylinders',
            field=models.IntegerField(default=0),
        ),
    ]
