# Generated by Django 2.2.11 on 2021-06-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0251_auto_20210611_2252'),
        ('facility', '0257_auto_20210618_1642'),
    ]

    operations = [
    ]
