# Generated by Django 2.2.11 on 2021-06-21 20:38

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_merge_20210621_2234'),
        ('facility', '0258_merge_20210622_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientexternaltest',
            name='aadhar_number',
            field=fernet_fields.fields.EncryptedTextField(null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='contact_number_of',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='date_of_sample_tested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='egene',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='hospital_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='hospital_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='hospitalization_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='icmr_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='icmr_patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='is_hospitalized',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='orf1b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='passport_number',
            field=fernet_fields.fields.EncryptedTextField(null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='pincode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='rdrp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='sample_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='sample_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.State'),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='symptom_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='symptoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='testing_kit_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='underlying_medical_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientexternaltest',
            name='village_town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientexternaltest',
            name='is_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientexternaltest',
            name='local_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.LocalBody'),
        ),
        migrations.AlterField(
            model_name='patientexternaltest',
            name='patient_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientexternaltest',
            name='srf_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
