# Generated by Django 2.2.11 on 2021-06-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0252_auto_20210620_2325'),
        ('facility', '0258_merge_20210620_2314'),
    ]

    operations = [
    ]
