# Generated by Django 2.2.11 on 2021-06-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0260_auto_20210629_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientexternaltestuploadhistory',
            options={'verbose_name_plural': 'patient external test upload histories'},
        ),
    ]
